---
# Install HttpFS
# Redhat / CentOS
- name: Install mapr-httpfs (Redhat / CentOS)
  yum: name=mapr-httpfs state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-httpfs (Debian / Ubuntu)
  apt: name=mapr-httpfs state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-httpfs (Suse)
  zypper: name=mapr-httpfs state=present
  when: ansible_os_family == 'Suse'

# Other actions
- name: Set owner mapr-system user
  file: path=/opt/mapr/httpfs owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes