---
# Create the MapR User and Group
- name: Create MapR Group
  group: name={{ mapr_group }} gid={{ mapr_group_gid }} state=present
- name: Create MapR User
  user: name={{ mapr_user }} comment="MapR default user" uid={{ mapr_user_uid }} group={{mapr_group}} groups={{ mapr_group }},root password={{ mapr_passwd | password_hash('sha512') }} createhome=yes state=present

