---
# Install MapR Kibana
- name: Install mapr-kibana
  package: name=mapr-kibana state=present
- name: Find Kibana Path
  find: paths="/opt/mapr/kibana/" patterns="kibana*" file_type=directory
  register: kibana_path_result
  failed_when: kibana_path_result.matched != 1
# fix for KIB-1
- name: Fix KIB-1
  lineinfile: dest={{ kibana_path_result.files[0].path }}/bin/export_cert.sh regexp="^CLUSTERNAME" line="CLUSTERNAME={{ cluster_name }}"
# Fix for OTSDB-4
- name: Set owner mapr-system user / OTSDB-4
  file: path=/opt/mapr/kibana owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes
