---
# Install MapR Pre-requisites software packages

  # Enable extra repo for Docker installation on AWS
  - name: Enable extra repo for Docker installation on AWS
    shell: "yum-config-manager --enable rhui-REGION-rhel-server-extras"
    ignore_errors: yes

  - name: Install libselinux-python tools
    yum: name=libselinux-python state=present

  - name: Set selinux config to permissive
    selinux: state=permissive policy=targeted
    when: ansible_distribution not in ('Amazon')

  - name: Selinux to permissive now
    command: setenforce permissive
    when: ansible_distribution not in ('Amazon')
    register: command_result
    failed_when: "command_result|failed and 'setenforce: SELinux is disabled' in command_result.msg"
    ignore_errors: yes

  - name: Install redhat-lsb-core
    yum: name=redhat-lsb-core state=present

  - name: Reread ansible_lsb facts
    setup: filter=ansible_lsb*

  - name: Disable iptables
    service: name=iptables state=stopped enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    when: ansible_lsb.major_release|int == 6
    ignore_errors: yes

  - name: Disable firewalld
    service: name=firewalld state=stopped enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    when: ansible_lsb.major_release|int == 7
    ignore_errors: yes

  - name: Check if running on Amazon EC2 machines
    shell: grep -s -o 'ec2' /sys/hypervisor/uuid | wc -l
    register: amazon_ec2_node

  - name: Install EPEL for non Amazon EC2 nodes
    yum: name=epel-release state=present
    when: amazon_ec2_node.stdout == '0'

  - name: Install EPEL on CentOS v6.x on Amazon EC2
    yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=installed
    when: ansible_lsb.major_release|int == 6 and amazon_ec2_node.stdout == '1'

  - name: Install EPEL on CentOS v7.x on Amazon EC2
    yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=installed
    when: ansible_lsb.major_release|int == 7 and amazon_ec2_node.stdout == '1'

  - name: Install NTP
    yum: name=ntp state=present

  - name: Restart NTP
    service: state=restarted name=ntpd

  - name: Ensure NTP is enabled
    service: name=ntpd enabled=yes state=started

  - name: Install nfs-utils to get rpcbind
    yum: name=nfs-utils state=installed

  - name: Ensure linux NFS services are disabled
    service: name={{item}} state=stopped enabled=no
    with_items:
      - nfs
      - nfslock

  - name: Ensure rpcbind starts
    service: name=rpcbind state=started enabled=yes

  - name: Ensure TCP retries are set to 5
    lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_retries2" line="net.ipv4.tcp_retries2=5"
#    notify: reload sysctl

  - name: Disable memory overcommit
    lineinfile: dest=/etc/sysctl.conf regexp="^vm.overcommit_memory" line="vm.overcommit_memory=0"
#    notify: reload sysctl
