---
# Install MapReduce2
# Redhat / CentOS
- name: Install mapr-mapreduce2 (Redhat / CentOS)
  yum: name=mapr-mapreduce2 state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-mapreduce2 (Debian / Ubuntu)
  apt: name=mapr-mapreduce2 state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-mapreduce2 (Suse)
  zypper: name=mapr-mapreduce2 state=present
  when: ansible_os_family == 'Suse'