---
# Install Open JDK
- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g' | cut -c-3
  register: java_version

- name: Download and Install Open JDK
  yum: name={{item}} state=present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
  when: java_version.stdout != "1.8"
