---
# Configure MapR monitoring

# Configure OpenTSDB
- name: Get OpenTSDB FQDNs
  set_fact: opentsdb_item={{ hostvars[item]['ansible_fqdn'] }}
  with_items:
    - "{{ groups['mapr-opentsdb'] }}"
  register: opentsdb_hosts
- name: Make OpenTSDB String
  set_fact: opentsdb_string={{ opentsdb_hosts.results | map(attribute='ansible_facts.opentsdb_item') | list | join(',')}}
- name: Configure.sh
  shell: /opt/mapr/server/configure.sh -R -OT {{ opentsdb_string }}
#  environment:
#    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket