---
# Install Hive WebHCat
# Redhat / CentOS
- name: Install mapr-hivewebhcat (Redhat / CentOS)
  yum: name=mapr-hivewebhcat state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-hivewebhcat (Debian / Ubuntu)
  apt: name=mapr-hivewebhcat state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-hivewebhcat (Suse)
  zypper: name=mapr-hivewebhcat state=present
  when: ansible_os_family == 'Suse'